label spare_ending:
    scene bg garage at bg with wipeleft
    "(In a large garage filled to the brim with carboard boxes, the exit waits for you, wide open.)"
    "(It's sunset already. The river outside quietly flows by.)"
    "(Just a few more steps, and you're out of here. Even more, and you'll be on the bus back home.)"
    "(It'll take a couple of hours to get back to HQ. You'll nap, probably so that by the time you get to your stop, you'll have enough energy to run up thousands of narrow stairs.)"
    "(And you'll reach your boss's office, and...)"
    "(...Well, what'll happen next?)"
    "(You'll {i}definitely {/i}get that bonus. If this isn't going \"above and beyond...\""
    "(Maybe you'll get a promotion. A better salary. Better benefits. A better home.)"
    "(A better life. Something you've worked towards for years.)"
    "(…And...)"
    "(And maybe that'll help you sort out the pit that's been growing in your stomach this whole-)"
    x "Finally going to take responsibility?"
    #"{b}[{/b}{b}Cautionne{/b}{b} appears with his gun]{/b}"
    "(Not now, kid! The last thing you need is {i}him{/i}{i} showing up and-{/i}-)"
    cr "I... I see my escape rooms have worked their magic. "
    cr "I didn't think it was possible but... you're feelingguilty, aren't you?"
    "(...Guilt? Is that what it is?)"
    "(Over something you didn't do?)"
    cr "All those years, you must've been so proud to wear that uniform! To be a brave soldier fighting for such a pristine, justice-seeking organization like that."
    "( You feel sick.)"
    cr "But it's not enough for you to {i}feel bad{/i}. "
    cr "'Cause if I let you go home, and get your bonuses, and sleep in your nice bed... you'll be stumbling over yourself to forget everything that happened here as fast as possible."
    cr "You... Or your boss, or the next agent... You'll storm in here and sweep away everything me and Dr. Danger fought for. "
    cr "S-someone better'll catch me and destroy this place. And STOP... STOP'll turn me into a nameless drone, like I was supposed to be."
    "(...He's shaking. He's trying to put on a brave face, but he's shaking.)"
    #"{b}[{/b}{b}cautionne{/b}{b} begins to break down]{/b}"
    cr "B-but I don't {i}want {/i}that, y'know?"
    cr "I... I don't {i}want {/i}to forget my home. My books, my bugs, my bed..."
    cr "And I don't {i}want {/i}to forget myself. I don't want to forget about collecting stickers, or eating pudding, or sewing my first pair of mittens."
    #"{b}[{/b}{b}Cautionne{/b}{b} is yelling now]{/b}"
    cr "And I don't {i}want {/i}to forget Dr. Danger! She {i}saved {/i}me! She {i}raised {/i}me! She {i}stood up for me{/i} when no one else did!"
    cr "And what did {i}STOP {/i}do? They MADE her a villain! They took EVERYTHING away from her! They KILLED her!"
    #"{b}[pause as {/b}{b}Cautionne{/b}{b} regains his composure a little]{/b}"
    "S-so, what're you gonna do now, lab rat? You've still got your \"service weapon\", don't you?"
    cr "C'mon. H-hit me with your best shot."
    cr "...Hit me!"
    cr "'Cause if you don't, I'll... I'll..."
    #"{b}[pause with the sound of the player's gun dropping to the floor]{/b}"
    "(...You can't deal with this anymore.)"
    "(You... you don't want to fight him.)"
    #"{b}[pause as {/b}{b}Cautionne's{/b}{b} expression changes]{/b}"
    cr "You... you're {i}not {/i}going to use your gun?"
    cr "...Heh. Haha. Hahahaha."
    #"{b}[gun clicks]{/b}"
    cr "T-then, on behalf of STOP... die."
    #"{b}[pause. Sound of the gun firing. {/b}{b}Screen goes black]{/b}"
    "(The bullet...)"
    "(...it only grazed your cheek.)"
    #"{b}[pause - a thud is heard as cautionne falls to the ground, stunned. The revolver clatters as he drops it.]{/b}"
    "(Huh? Cautionne... fell?)"
    "(What's going...)"
    #"{b}[pause as cautionne spare end cg fades in]{/b}"
    cr "I... I missed."
    cr "I had the muzzle aimed at your head. The bullets loaded. "
    cr "And I missed. First try."
    "(Cautionne's gaze is vacant.)"
    "(It's the same gaze as that boy in the scrapbook.)"
    "(That alone makes the pit in your stomach sink even deeper.)"
    "(So to fill it... you say something really, really stupid.)"
    "You know... you could've fired again. I'm at contact shot distance."
    cr "…Pft."
    cr "No, I couldn't have. Trying to kill you... was a lot more tiring than I thought it would be."
    "Tiring?"
    cr "…"
    "(...Ah.)"
    cr "Go. This is what you wanted, right?"
    cr "The exit's right there. "
    cr "Go back to your home. Your TV. Your{i} money.{/i}"
    cr "I was fooling myself, thinking I could do what Dr. Danger did for me."
    cr "So, go. "
    cr "I hope the guilt eats at you for the rest of your fucking life."
    #"{b}[pause when the exit {/b}{b}bg{/b}{b} shows again. Camera shows the player getting up, and leaving for the {/b}{b}exit{/b}{b}]{/b}"
    "(Slowly, you make your way towards the exit.)"
    #"{b}[pause]{/b}"
    "(When you finally make it outside, you turn back.)"
    "(The boy's still sitting there.)"
    "(Legs splayed haphazardly. Arms, floppy. Still staring at you.)"
    #"{b}[pause]{/b}"
    "(You stare back at him. Give him a curt nod.)"
    "(He doesn't react.)"
    #"{b}[pause]{/b}"
    "(So, without another word, you-)"
    cr "...Hey lab rat."
    "(You turn back, and see him forcing an attempt at a villainous grin.)"
    #"{b}[{/b}{b}pause, and{/b}{b} show a variant of {/b}{b}Cautionne's{/b}{b} spare end CG.]{/b}"
    cr "If you really feel that bad about it..."
    cr "I did sneak copies of everything you've seen here onto your device. I found your address while you were looking around."
    cr "Pretty devious idea, right? Downright heinous."
    "(He takes a deep breath. Then exhales.)"
    cr "Alright. Here's"
    cr "\"STOP agent stakes reputation, credentials, leaks internal docs to all four corners of the net.\""
    "CuationneNot a bad headline. Could make for a half-decent start to a villainous career."
    #"{b}[pause]{/b}"
    cr "Your choice, obviously. But I know what I'm talking about."
    cr "After all, I {i}am{/i}{i} {/i}a supervillain."
    #"{b}[pause as {/b}{b}Cautionne's{/b}{b} footsteps are heard slowly walking off]{/b}"
    #"{b}(CG of Cautionne's stoplight hairclip shown on the floor.){/b}"
    #"{b}(The player is shown picking it up with their hand.]{/b}"
    #"{b}[Then, the screen goes black]{/b}"
    #"{b}[SPARE END]{/b}"
    #"{b}[credits roll]{/b}""
    return