label neutral_ending:
    #"{b}[pause – walking sounds play as the exit BG appears]{/b}"
    scene bg garage at bg with wipeleft
    "(There's the exit, right up ahead.)"
    #"{b}[pan across {/b}{b}bg{/b}{b} to show {/b}{b}all of{/b}{b} the items there]{/b}"
    "(It's in the middle of a big, garage space; one filled with boxes of all shapes and sizes. Maybe it's for storing tools or materials.)"
    "(You don't really want to find out. Like the hallway before it, this room's completely unremarkable.)"
    "(And besides, you've had enough of exploring.)"
    #"{b}[pause]{/b}"
    "(...All that said, you weren't expecting your escape to be so... straightforward.)"
    "(The exit's wide open. If you walked through right now, you'll-)"
    #"{b}[quick footsteps sound out]{/b}"
    "(Aw, crap. You jinxed yourself.)"
    "H-hello? Who's there?"
    x "So, you {i}finally {/i}made it. Did you like my games, lab rat?"
    #"{b}[show {/b}{b}Cautionne{/b}{b} shooting CG]{/b}"
    "(A... a {i}gun?{/i})"
    "(Why does he have a gun? Someone his age shouldn't-)"
    "(No, it's a fake, isn't it? Of course – it's just a practical joke of his! )"
    "Um... I'm glad you're having fun and all, but I really should get going. See, adults have these things called “jobs”, and-"
    #"{b}[Pause – sound of {/b}{b}Cautionne{/b}{b} firing a bullet into your kneecap. Screen turns black for a pause. ]{/b}"
    "(Oh. My knee.)"
    "(Aah?)"
    "(Aaaaaaah?!)"
    "(AaaaaAAAAaaAaAAAAaaAAAAH?!?!?!?)"
    #"{b}[the player collapses on the floor]{/b}"
    "(Shit. Shit, shit, shit.)"
    "(I can't believe – I made such a {i}stupid {/i}mistake!)"
    "(And I can't... Haa... I can't... stand any more!)"
    "(Wha... what am I gonna do? How am I gonna get out of here {i}now?{/i})"
    #"{b}[footsteps sounds as{/b}{b} Cautionn{/b}{b}e walks over.]{/b}"
    cr "Patronize me at your own risk."
    cr "...Is what I should've said before firing, but I'm still new at this part."
    cr "Only a little newer than you, lab rat. "
    cr "It's why you don't scare me. You're just a low-level nobody with a hand-to-mouth life."
    cr "That's why you did this mission, right? ‘Cause you wanted that sweet, fat, paycheck?"
    "(…I... I want... to say something...)"
    "(But, haah... I'm shaking... and sweating... everywhere....)"
    "(All I can do... is open my eyes...)"
    #"{b}[Show the bottom of his shooting CG]{/b}"
    "Struggling just to open your mouth? That's almost cute, in a gross kind of way."
    cr "You've never experienced this much pain before, have you?"
    if most_explored == 1:
        cr "In fact, it seems like you haven't experienced much of anything."
        cr "If I let you go, would your bosses even care?"
        cr "After all, you're not much of an investigator."
        cr "So, how ‘bout I save you all the exit interview and put things to an end here."
        "(N-no... I can still get up! If I... crawl all the way back... they'll... definitely forgive me...)"
        #"{b}[pan up to his face]{/b}"
        cr "Hm... I'll admit, I'm curious."
        cr "When you're gone, will STOP eulogize you? Or will they just write you off as another wasted asset?"
        cr "...Hee hee. I'm undecided."
        #"{b}[the trigger clicks]{/b}"
        cr "But I wouldn't be much of a scientist if I didn't test my hypotheses."
        #"{b}[the gun fires – scene cuts to black]{/b}"
        #"{b}[NEUTRAL END – ROOM 1 VARIANT]{/b}"
        #"{b}[{/b}{b}Cautionne{/b}{b} laughing as the ending text pops up]{/b}"
        #"{b}[credits roll]{/b}"
    elif most_explored == 2:
        cr "But as much as I sympathize... I just can't let you go."
        cr "You got your muddy paws on some {i}confidential {/i}information. Stuff way above your paygrade."
        cr "So, I'm afraid I'll have to end things here."
        #"{b}[pan up to his face]{/b}"
        cr "No hard feelings. I know you were just doing your job."
        cr "But see, there's a little {i}conflict of interest{/i} between you and me."
        cr "Besides, I've got to finish what Dr. Danger started. That's {i}my {/i}{i}job{/i}, now that she's gone."
        #"{b}[the trigger clicks]{/b}"
        cr "And by the time I'm finished, they'll be begging for her to come back."
        #"{b}[the gun fires]{/b}"
        #"{b}[NEUTRAL END – ROOM 2 VARIANT]{/b}"
        #"{b}[{/b}{b}Cautionne{/b}{b} laughing more menacingly as the {/b}{b}endin{/b}{b} text pops up]{/b}"
        #"{b}[credits roll]{/b}"
    else:
        cr "Want a fun fact? You'll {i}definitely {/i}find it interesting."
        cr "The pain you're feeling right now... is only a thousandth of the pain I went through."
        cr "I wish I was exaggerating, but they came up with very accurate, scientific measurements for this kind of thing. {i}Only one thousandth.{/i}"
        cr "You read Dr. Danger's diary, right? You know what STOP did to me."
        cr "Getting up from my bed took weeks. Walking with my new legs took months. I still twitch and faint 'cause of the shit they put in my brain."
        cr "You'll never know what that's like. Being a {i}real {/i}lab rat."
        #"{b}[pan up to his face]{/b}"
        cr "I {i}won't{/i} let anyone else live through what I did."
        cr "You weren't there. You weren't in charge. "
        cr "But after everything you people did to me... No, to {i}us...{/i}"
        #"{b}[{/b}{b}cautione{/b}{b} is on the verge of tears]{/b}"
        cr "I... I..."
        #"{b}[the trigger clicks]{/b}"
        cr "...I just can't forgive someone who'd brush that aside."
        #"{b}[the gun fires]{/b}"
        #"{b}[{/b}{b}Cautionne{/b}{b} is heard crying softly as the ending text pops up]{/b}"
        #"{b}[NEUTRAL END – ROOM 3 VARIANT]{/b}"