label kill_ending:
    #"{b}[pause – walking sounds play as the exit BG appears]{/b}"
    scene bg garage at bg with wipeleft
    "({i}Finally. {/i}There's the exit.)"
    "(And the path is clear- no guards, no traps. Just a big garage, littered with cardboard boxes.)"
    "(Huh. You weren't expecting your escape to be so... simple.)"
    #"{b}[quick footsteps sound out]{/b}"
    "(Scratch that. You spoke too soon.)"
    x "Identify yourself!"
    x "How many guesses will you need this time?"
    #"{b}[show {/b}{b}Cautionne{/b}{b} shooting CG{/b}{b}]{/b}"
    "No more TV screens, huh?"
    cr "Don't need them. Not if {i}I'm{/i} going to finish what Dr. Danger started."
    "Using{i} that?{/i} Kid, you shouldn't be wielding-"
    cr "Shut up and let me improvise, lab rat."
    cr "I didn't {i}actually {/i}think you'd make it this far."
    cr "But, alas, as it turns out... your puzzle-solving skills are... decent."
    cr "In another life, you'd make {i}quite {/i}the sidekick."
    "...Well, maybe if you'd let me go-"
    cr "No more hypotheticals. You're {i}dangerous,{/i} lab rat, and I just can't do that."
    "(The brat's got bravado - you'll give him that. He's keeping that revolver remarkably steady, even though he's shaking all over.)"
    "(But he's still just a kid. Might never have evenwielded a weapon before, for all his big talk.)"
    "(On the other hand... you're a STOP agent.)"
    "(You can draw and fire a gun faster than someone can say “knife”. It's the first thing they teach you as a trainee.)"
    "(He's scared, but he's not going to hesitate any longer.)"
    "(You exhale, and before his finger can snake itself over the trigger-)"
    "(-you raise your gun towards his torso.)"
    #"{b}[bang – with a cut to black]{/b}"
    "(You half expected that freak to go down cackling, like something out of a movie. A villain shrieking with laughter even as they're plugged with thousands of rounds.)"
    #"{b}[show bleeding {/b}{b}cautionne{/b}{b} cg with a slow fade]{/b}"
    "(...But Cautionne's final moments are silent.)"
    "(He stutters out a pained gasp.)"
    "(His gun clatters on the floor.)"
    "(He reaches forward. He struggles to grab something you can't see.)"
    #"{b}[pause]{/b}"
    "(He falls.)"
    #"{b}[thud sound plays and the screen cuts to black again]{/b}"
    "(He doesn't move again.)"
    #"{b}[pause for a few seconds]{/b}"
    #"{b}[show dead {/b}{b}Cautionne{/b}{b} CG with a slow fade.]{/b}"
    "(As you walk from the garage, you do your best to ignore Cautionne's lifeless body.)"
    "(From the corner of your eye, you watch his blood ooze onto the floor. Once a better agent comes here to gather evidence, they'll mop the stains and burn the body.)"
    "(The sight of his blood at the edge of your vision fills you with exhaustion. You just want to get out of here and let someone higher up sort this shit out.)"
    "(But as you leave, you can't help but think to yourself, “That was easy.”)"
    #"{b}[pause]{/b}"
    "(Easier than it should've been, maybe.)"
    #"{b}[pause]{/b}"
    "(Or maybe not.)"
    "(...But one thing's for sure. There's one less villain out there now.)"
    "(One less threat.)"
    "(One less thorn in STOP's side.)"
    #"{b}[pause]{/b}"
    "(When you go to write up your report, that's all you'll be able to say.)"
    #"{b}[pause and last cg fades to black]{/b}"
    #"{b}[KILL END]{/b}"
    #"{b}[credits roll]{/b}"
    return